index_fraccionar:
    pattern:  /index/{id}
    defaults: { _controller: NossisBundle:Fraccionar:index }
    
show_fraccionar:
  pattern:  /show/{id}
  defaults: { _controller: NossisBundle:Fraccionar:show }
  
listar_fraccionar:
  pattern:  /listar/
  defaults: { _controller: NossisBundle:Fraccionar:listar }
  
fraccionar_lote_stock:
  pattern:  /fraccionar/lote/stock/{id}
  defaults: { _controller: NossisBundle:Fraccionar:lote }