index_retiro:
    pattern:  /index
    defaults: { _controller: NossisBundle:Retiro:index }

new_retiro:
    pattern:  /nuevo
    defaults: { _controller: NossisBundle:Retiro:new }

edit_retiro:
    pattern:  /editar/{id}
    defaults: { _controller: NossisBundle:Retiro:edit }

list_retiro:
    pattern:  /listar
    defaults: { _controller: NossisBundle:Retiro:listar }

show_retiro:
    pattern:  /show/{id}
    defaults: { _controller: NossisBundle:Retiro:show }

confirmar_retiro:
    pattern:  /confirmar/{id}
    defaults: { _controller: NossisBundle:Retiro:confirmar }

imprimir_retiro:
    pattern:  /imprimir/{id}
    defaults: { _controller: NossisBundle:Retiro:imprimir }