nossis_homepage:
    pattern:  /index
    defaults: { _controller: NossisBundle:Default:index }

nossis_homepage2:
    pattern:  /
    defaults: { _controller: NossisBundle:Default:index }
    
nossis:
    resource: "@NossisBundle/Resources/config/stock-routing.yml"
    prefix:   /stock

despachar:
    resource: "@NossisBundle/Resources/config/retiro-routing.yml"
    prefix:   /despachar

RetiroStock:
    resource: "@NossisBundle/Resources/config/retiro-stock-routing.yml"
    prefix:   /retiro/stock

sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
FraccionarStock:
    resource: "@NossisBundle/Resources/config/fraccionar-routing.yml"
    prefix:   /fraccionar

Listado:
    resource: "@NossisBundle/Controller/ListadoController.php"
    type:     annotation

Devolucion:
    resource: "@NossisBundle/Controller/DevolucionController.php"
    type:     annotation
    
ExportacionAlma:
    resource: "@NossisBundle/Controller/ExportacionAlmaController.php"
    type:     annotation
    
EnvaseIngreso:
    resource: "@NossisBundle/Controller/EnvaseIngresoController.php"
    type:     annotation
    
Envase:
    resource: "@NossisBundle/Controller/EnvaseController.php"
    type:     annotation
    
EnvaseRetiro:
    resource: "@NossisBundle/Controller/EnvaseRetiroController.php"
    type:     annotation