parameters:
#    nossis.example.class: Nossis\NossisBundle\Example

services:
#    nossis.example:
#        class: %nossis.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
