ingresar_stock:
    pattern:  /ingresar
    defaults: { _controller: NossisBundle:Stock:ingresar }

agregar_stock:
    pattern:  /agregar
    defaults: { _controller: NossisBundle:Stock:agregar }
 
index_stock:
    pattern:  /index
    defaults: { _controller: NossisBundle:Stock:index }

