ingresar_stock:
    pattern:  /ingresar
    defaults: { _controller: NossisBundle:Stock:ingresar }

agregar_stock:
    pattern:  /agregar
    defaults: { _controller: NossisBundle:Stock:agregar }
 
index_stock:
    pattern:  /index
    defaults: { _controller: NossisBundle:Stock:index }
    
trazladar_stock:
    pattern:  /trazladar/{id}
    defaults: { _controller: NossisBundle:Stock:trazladar }

listar_ingreso_stock:
    pattern:  /listar/ingreso
    defaults: { _controller: NossisBundle:Stock:listarIngreso }
    
listar_stock:
    pattern:  /listar/stock
    defaults: { _controller: NossisBundle:Stock:listarStock }

show_stock:
    pattern:  /show/{id}
    defaults: { _controller: NossisBundle:Stock:show }

editar_stock:
    pattern:  /editar/{id}
    defaults: { _controller: NossisBundle:Stock:editar }

imprimir_stock:
    pattern:  /imprimir/{id}
    defaults: { _controller: NossisBundle:Stock:imprimir }
    
fraccionar_stock:
    pattern:  /fraccionar/{id}
    defaults: { _controller: NossisBundle:Stock:fraccionar }
    
trazladar_lote_stock:
    pattern:  /trazladar/lote/stock
    defaults: { _controller: NossisBundle:Stock:trazladarLote }

lote_trazladar_stock:
    pattern:  /trazladar/lote/stocks/{lote}/{area}
    defaults: { _controller: NossisBundle:Stock:trazladarLoteArea }