_nossis:
    resource: "@NossisBundle/Resources/config/routing.yml"
    prefix:   /
    
sonata:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

