<?php

namespace Nossis\NossisBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;
use DateTime;

/**
 * EnvaseIngresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvaseIngresoRepository extends EntityRepository
{
    
    public function findByFecha(DateTime $desde, DateTime $hasta)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('e')
            ->from('NossisBundle:EnvaseIngreso', 'e')
            ->andwhere ('e.fecha >= :desde')
            ->andWhere('e.fecha <= :hasta')
            ->setParameters(array('desde' => $desde, 'hasta' => $hasta))
            ->getQuery();
        return $query->getResult();
        
    }
    
}
