<?php

namespace Nossis\NossisBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * ItemExportacionAlmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemExportacionAlmaRepository extends EntityRepository
{
}
