<?php

namespace Nossis\NossisBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * RetiroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetiroRepository extends EntityRepository
{
    public function findLote($lote)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('r')
            ->from('NossisBundle:Retiro', 'r')
            ->join('r.stocks', 'rs')
            ->join('rs.stock', 's')
            ->where('s.lote LIKE :lote')
            ->GroupBy('r.nroOrden')
            ->setParameters(array('lote' => $lote))
            ->getQuery();
        return $query->getResult();
    }
    
    public function findClientes($cliente)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('r')
            ->from('NossisBundle:Retiro', 'r')
            ->innerJoin('r.stocks', 'rs')
            ->where('rs.cliente = :cliente')
            ->orderBy('r.nroOrden', 'DESC')
            ->setParameters(array('cliente' => $cliente))
            ->getQuery();
        return $query->getResult();
    }
}
