<?php

namespace Nossis\NossisBundle\Entity\Repositorio;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    
    public function findLast($limit=20)
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('s')
            ->from('NossisBundle:Stock', 's')
            ->orderBy('s.id', 'DESC')
            ->setMaxResults($limit)
            ->getQuery();
        return $query->getResult();
        
    }
    
    public function mostrarStockActualLote()
    {
        $em = $this->getEntityManager();
        $query = $em->createQueryBuilder()
            ->select('s.lote, count(s.id) as palets, sum(s.actual) as total, p.nombre')
            ->from('NossisBundle:Stock', 's')
            ->join('s.producto', 'p')
            ->where('s.actual > 0')
            ->GroupBy('s.lote')
            ->orderBy('p.nombre')
            ->getQuery();
        return $query->getResult();
    }
    
    public function mostrarStockActualLoteFecha($desde, $hasta, $producto = null)
    {
        $em = $this->getEntityManager();
        if ($producto != null)
        {
        $query = $em->createQueryBuilder()
            ->select('s.lote, count(s.id) as palets, sum(s.actual) as total, p.nombre')
            ->from('NossisBundle:Stock', 's')
            ->join('s.producto', 'p')
            ->where('s.actual > 0')
            ->andWhere('s.fechaIngreso >= :desde')
            ->andWhere('s.fechaIngreso <= :hasta')
            ->andWhere('p.id = :producto')
            ->GroupBy('s.lote')
            ->orderBy('p.nombre')
            ->setParameters(array('desde' => $desde, 'hasta' => $hasta, 'producto' => $producto))
            ->getQuery();
        }else{
            $query = $em->createQueryBuilder()
            ->select('s.lote, count(s.id) as palets, sum(s.actual) as total, p.nombre')
            ->from('NossisBundle:Stock', 's')
            ->join('s.producto', 'p')
            ->where('s.actual > 0')
            ->andWhere('s.fechaIngreso >= :desde')
            ->andWhere('s.fechaIngreso <= :hasta')
            ->GroupBy('s.lote')
            ->orderBy('p.nombre')
            ->setParameters(array('desde' => $desde, 'hasta' => $hasta))
            ->getQuery();
        }
        return $query->getResult();
    }
    
    public function findAllFecha($desde, $hasta, $producto = null)
    {
        $em = $this->getEntityManager();
        if ($producto != null)
        {
            $query = $em->createQueryBuilder()
                ->select('s')
                ->from('NossisBundle:Stock', 's')
                ->where('s.actual > 0')
                ->andWhere('s.fechaIngreso >= :desde')
                ->andWhere('s.fechaIngreso <= :hasta')                    
                ->andWhere('s.producto = :producto')
                ->setParameters(array('desde' => $desde, 'hasta' => $hasta, 'producto' => $producto))
                ->getQuery();
        }else{
            $query = $em->createQueryBuilder()
                ->select('s')
                ->from('NossisBundle:Stock', 's')
                ->where('s.actual > 0')
                ->andWhere('s.fechaIngreso >= :desde')
                ->andWhere('s.fechaIngreso <= :hasta')
                ->setParameters(array('desde' => $desde, 'hasta' => $hasta))
                ->getQuery();
        }
        return $query->getResult();
    }
    
    
}
