<?php

namespace Nossis\NossisBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EnvaseEmpresaRepositorio
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvaseEmpresaRepositorio extends EntityRepository
{
}
