<?php

namespace Nossis\NossisBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DevolucionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevolucionRepository extends EntityRepository
{
}
